# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fbc48186901335a17ba867ac27a33fd0fc659653531421d02bbdf1f16e5331aa482bf83cb92f93d9f63bde1205a06aca47e93d210b2475e7a1e650cd99a6de1f

test:
  secret_key_base: 60995c05cfb1d86e807cef1e602a0073f736d5b38f3b5c5ff78e165af9ff1c877bf0572d517dbc286a0a89d8955bedccb2cf977bee25e3849427f78939b6d17e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
